# Generated by Django 4.0 on 2023-04-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='ShopifyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_url', models.CharField(max_length=256)),
                ('api_key', models.CharField(max_length=256)),
                ('api_secret', models.CharField(max_length=256)),
                ('access_token', models.CharField(max_length=256)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=256)),
                ('id_options', models.CharField(choices=[('Driver License', 'Driver License'), ('Postal ID', 'Postal ID')], max_length=64)),
                ('id_image', models.ImageField(upload_to='')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=64)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(max_length=70)),
                ('description', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('live', models.BooleanField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.personaccount')),
            ],
        ),
    ]
